### ISSUE TITLE
lora推理报错

### ISSUE THREAD

**Issue by troycjj** [ssbuild/qwen_finetuning#4]
![image](https://github.com/ssbuild/qwen_finetuning/assets/52953954/5144d4c1-26b7-42b9-b235-dc475c40cec6)
Traceback (most recent call last):
  File "infer_lora_finetuning.py", line 68, in <module>
    response, history = model.chat(tokenizer, input, history=[],)
  File "/root/miniconda3/lib/python3.8/site-packages/aigc_zoo/model_zoo/qwen/llm_model.py", line 52, in chat
    max_window_size = self.generation_config.max_window_size
AttributeError: 'GenerationConfig' object has no attribute 'max_window_size'

**Comment by ssbuild** [comment]
官方仓库更改了部分配置，已改了配置相关信息， 看下readme 更新说明。
