### ISSUE TITLE
deep_training 这个包里报错 。挺奇怪。

### ISSUE THREAD

**Issue by wellcasa** [ssbuild/qwen_finetuning#7]
Rank(Worker): 0 caught unknown unhandled exception:
Exception type: AssertionError
Detail:
Traceback (most recent call last):
File "/checkpoint/binary/train_package/train.py", line 26, in <module>
qwen_train( qwen_args, output_dir)
File "/checkpoint/binary/train_package/src/mdl/qwen/train.py", line 122, in train
trainer.fit(pl_model, train_dataloaders=train_datasets)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
call._call_and_handle_interrupt(
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
self._run(model, ckpt_path=ckpt_path)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
results = self._run_stage()
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
self.fit_loop.run()
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
self.advance()
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
self.epoch_loop.run(self._data_fetcher)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
self.advance(data_fetcher)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 218, in advance
batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 185, in run
self._optimizer_step(kwargs.get("batch_idx", 0), closure)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 260, in _optimizer_step
call._call_lightning_module_hook(
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 144, in _call_lightning_module_hook
output = fn(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/core/module.py", line 1256, in optimizer_step
optimizer.step(closure=optimizer_closure)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/core/optimizer.py", line 155, in step
step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/strategy.py", line 225, in optimizer_step
return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/plugins/precision/amp.py", line 76, in optimizer_step
closure_result = closure()
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
self._result = self.closure(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 126, in closure
step_output = self._step_fn()
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 307, in _training_step
training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 291, in _call_strategy_hook
output = fn(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/strategy.py", line 367, in training_step
return self.model.training_step(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/transformer_base.py", line 552, in training_step
outputs = self.compute_loss(**batch)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/transformer_base.py", line 371, in compute_loss
return self.model.compute_loss(**kwargs)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/transformer_base.py", line 117, in compute_loss
return self.model(*args, **batch)
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
output = old_forward(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/qwen/modeling_qwen.py", line 964, in forward
transformer_outputs = self.transformer(
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
output = old_forward(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/qwen/modeling_qwen.py", line 780, in forward
outputs = torch.utils.checkpoint.checkpoint(
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
return CheckpointFunction.apply(function, preserve, *args)
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 107, in forward
outputs = run_function(*args)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/qwen/modeling_qwen.py", line 776, in custom_forward
return module(*inputs, use_cache, output_attentions)
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
output = old_forward(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/qwen/modeling_qwen.py", line 538, in forward
attn_outputs = self.attn(
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
output = old_forward(*args, **kwargs)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/qwen/modeling_qwen.py", line 448, in forward
context_layer = self.core_attention_flash(q, k, v)
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.local/lib/python3.8/site-packages/deep_training/nlp/models/qwen/modeling_qwen.py", line 140, in forward
assert all((i.dtype in [torch.float16, torch.bfloat16] for i in (q, k, v)))
AssertionError

**Comment by ssbuild** [comment]
closed issue有这个问题解决方案，代码更新，如果不是a100 h100的卡，可以关掉flash att.
https://github.com/ssbuild/qwen_finetuning/issues/5#issuecomment-1676800007

**Comment by wellcasa** [comment]
根据你说的，在lora模式下是可以工作的。但是sft报错了

Traceback (most recent call last):
  File "/checkpoint/binary/train_package/train.py", line 35, in <module>
    qwen_train( qwen_args, output_dir)
  File "/checkpoint/binary/train_package/src/mdl/qwen/train.py", line 140, in train
    trainer.fit(pl_model, train_dataloaders=train_datasets)
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 91, in launch
    return function(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 949, in _run
    self.strategy.setup(self)
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/deepspeed.py", line 347, in setup
    self.init_deepspeed()
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/deepspeed.py", line 451, in init_deepspeed
    self._initialize_deepspeed_train(model)
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/deepspeed.py", line 487, in _initialize_deepspeed_train
    model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
  File "/root/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/deepspeed.py", line 416, in _setup_model_and_optimizer
    deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
  File "/root/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 157, in initialize
    config_class = DeepSpeedConfig(config, mpu)
  File "/root/.local/lib/python3.8/site-packages/deepspeed/runtime/config.py", line 768, in __init__
    self._initialize_params(copy.copy(self._param_dict))
  File "/root/.local/lib/python3.8/site-packages/deepspeed/runtime/config.py", line 801, in _initialize_params
    assert not (self.fp16_enabled
AssertionError: bfloat16 and fp16 modes cannot be simultaneously enabled

**Comment by wellcasa** [comment]
应该是 两者在deepspeed有冲突

**Comment by ssbuild** [comment]
检查代码是否是新代码，精度问题应该fixed了吧 。
测试了 flash att 和 关掉 flash att 都可以正常训练。

**Comment by wellcasa** [comment]
用了最新代码， 我两台机器，我测试发现
torch.cuda.is_bf16_supported() is False 代码好用，
torch.cuda.is_bf16_supported() is True 代码报错，AssertionError: bfloat16 and fp16 modes cannot be simultaneously enabled

**Comment by ssbuild** [comment]
> 用了最新代码， 我两台机器，我测试发现 torch.cuda.is_bf16_supported() is False 代码好用， torch.cuda.is_bf16_supported() is True 代码报错，AssertionError: bfloat16 and fp16 modes cannot be simultaneously enabled

这两个分别对应什么卡？

**Comment by ssbuild** [comment]
https://github.com/ssbuild/qwen_finetuning/blob/87f59d077ddbe333db3548f8e78b725e82ae7a40/train.py#L89
torch.cuda.is_bf16_supported() = True ， 开启配置精度自动检测后， 会修改配置config.bf16 = True  ， 将模型类型转换bf16.  在a100 测试是正常的。

**Comment by wellcasa** [comment]
> 

False V100 
True A100

**Comment by wellcasa** [comment]
> https://github.com/ssbuild/qwen_finetuning/blob/87f59d077ddbe333db3548f8e78b725e82ae7a40/train.py#L89
> 
> 
> torch.cuda.is_bf16_supported() = True ， 开启配置精度自动检测后， 会修改配置config.bf16 = True ， 将模型类型转换bf16. 在a100 测试是正常的。

嗯 我也是这么想，但是我发现，我的机器，torch.cuda.is_bf16_supported() is True  但是我打印QwenConfig的里面并不是

QWenConfig {
  "activation": "swiglu",
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "QWenLMHeadModel"
  ],
  "attn_dropout_prob": 0.0,
  "attn_pdrop": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_qwen.QWenConfig",
    "AutoModelForCausalLM": "modeling_qwen.QWenLMHeadModel"
  },
  "bf16": false,
  "bias_dropout_fusion": true,
  "bos_token_id": 151643,
  "emb_dropout_prob": 0.0,
  "embd_pdrop": 0.1,
  "eos_token_id": 151643,
  "ffn_hidden_size": 22016,
  "fp16": false,
  "fp32": false,
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "initializer_weight": false,
  "intermediate_size": 22016,
  "kv_channels": 128,
  "layer_norm_epsilon": 1e-05,
  "max_position_embeddings": 8192,
  "model_type": "qwen",
  "no_bias": true,
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "onnx_safe": null,
  "params_dtype": "torch.bfloat16",
  "pos_emb": "rotary",
  "quantization_bit": 0,
  "resid_pdrop": 0.1,
  "return_dict": false,
  "rotary_emb_base": 10000,
  "rotary_pct": 1.0,
  "scale_attn_weights": true,
  "seq_length": 2048,
  "task_specific_params": {
    "learning_rate": 2e-05,
    "learning_rate_for_task": 2e-05
  },
  "tie_word_embeddings": false,
  "tokenizer_type": "QWenTokenizer",
  "transformers_version": "4.30.2",
  "use_cache": true,
  "use_dynamic_ntk": true,
  "use_flash_attn": true,
  "use_logn_attn": true,
  "vocab_size": 151936
}

**Comment by wellcasa** [comment]
和安装包 aigic-zoo有关系？我直接装最新版本，没有git装，git装老是超时。

**Comment by ssbuild** [comment]
> num_hidden_layers

跟aigic-zoo没关系 。
config 的打印是在模型前 。 自动检测是模型初始化。

可以强行修改config.json 试试 
"bf16":  true,
"fp16": false,
"fp32": false,

**Comment by wellcasa** [comment]
哦哦。let me try.

**Comment by wellcasa** [comment]
> > num_hidden_layers
> 
> 跟aigic-zoo没关系 。 config 的打印是在模型前 。 自动检测是模型初始化。
> 
> 可以强行修改config.json 试试 "bf16": true, "fp16": false, "fp32": false,

这样是可以的，但是总觉的每次配置配置完，还需要在外部在强制修改，怪怪的。

**Comment by ssbuild** [comment]
deep_training 是什么版本？

**Comment by wellcasa** [comment]
[46/deep_training-0.1.17.post0-py3-none-any.whl]
